[tools]
admin_port = 18791
script = ALL
package_path = /root/databaas/packages
node_port=18792
kafka_servers=10.128.0.29:9092

[zk]
hosts = 10.128.0.29:2181
ip_dir =  /dags/schedule_platform/online/admin_ip
