# Generated by Django 4.2.4 on 2025-08-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horae', '0017_uploadhistory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='graph',
            field=models.TextField(null=True),
        ),
    ]
